arch:
  - amd64
  - ppc64le
language: go
sudo: false
go:
  - 1.11.x
  - stable

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get -t -v ./...

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
